### ISSUE TITLE
Fix class not resolved in param declaration

### ISSUE THREAD

**Issue by VasLem** [nextflow-io/language-server#47]
How to deal with "undefined" variables, that are loaded by nextflow.config or exist in the environment?

![image](https://github.com/user-attachments/assets/5f27e941-f40c-4e2d-a260-2b03fa7305b6)

Is there a way to silence these errors? If so it would be nice to have a quick fix above for ignoring that error at a line basis.

**Comment by VasLem** [comment]
Alright, thanks, I see, I tried to make this change, but I receive a "System is not defined" issue now.

![image](https://github.com/user-attachments/assets/52de3444-c7f4-45d1-8fbd-928cf378f7bd)

I understand that silencing an error is not a good practice if you are planning to have a strictly formal language specification. Also, I was not aware of that page you referenced, it clears out several issues I had regarding Groovy and Nextflow compliance.

**Comment by VasLem** [comment]
Another thing popped up after I implemented the change, when I define an `env` var within  a `nextflow.config` profile, it doesn't seem to be picked up by `System.getenv`  within a process, I am left with null...

**Comment by bentsherman** [comment]
I am seeing the issue with System.getenv in a param declaration, I will look into it

Regarding the `env` config scope, those variables are exposed to the task environment, not the pipeline script

**Comment by VasLem** [comment]
The thing is that until now, the env vars were picked just fine by the script as well... Wasn't this not intended?

**Comment by bentsherman** [comment]
Interesting, that is not the intention, see the relevant docs here:

https://nextflow.io/docs/latest/reference/config.html#env

Can you share a minimal test case where an env in the config is printed in the script?

**Comment by bentsherman** [comment]
Actually it was pretty easy to replicate:

```groovy
env {
    FOO = 'bar!'
}
```

```groovy
println "${FOO}"
```

```console
$ nextflow run test.nf

 N E X T F L O W   ~  version 24.10.0

Launching `test.nf` [shrivelled_almeida] DSL2 - revision: 320593a247

bar!
```

@pditommaso FYI, it looks like config env settings are exposed in the script?

**Comment by VasLem** [comment]
(...it would be great to have this non-intended behavior stay as is, changing profiles and having env variables adapt to these changes is really, really helpful 🥹)

**Comment by pditommaso** [comment]
> FYI, it looks like config env settings are exposed in the script?

Not 100% sure it was desired. We may need to review along with the mechanism to access env variables both in config and script files. 

Maybe, it could be used `env.` both to define and access env variables both for tasks and script

**Comment by bentsherman** [comment]
> Maybe, it could be used env. both to define and access env variables both for tasks and script

I was thinking the same, `env()` would be nicer than `System.getenv()` and consistent with `env()` process output

**Comment by bentsherman** [comment]
The issue with `System.getenv()` will be fixed in the next patch release. Also, a new `env()` function will be introduced in Nextflow 24.11.0-edge
