### ISSUE TITLE
Variable was declared but not used

### ISSUE THREAD

**Issue by VasLem** [nextflow-io/language-server#48]
Minor issue is that defining shell variables within the shell part of the process and then using them within the command string is not supported. The server complains about variable being declared but not used. Example:

```
process example {    
    shell:
    njobs = Math.ceil((task.cpus as int) / 4) as int
    '''
    echo "Number of jobs to be used: !{njobs}"
    '''
}
```

**Comment by VasLem** [comment]
Until you push the latest change regarding the problem with the duplication or removal of backslashes to the formal vscode repo, the only possible way to be able to use the server is to replace all the "script" with "shell", that's why I faced that issue.

**Comment by bentsherman** [comment]
Do you have auto-format on save enabled? You can disable that in the vscode settings so that the formatting doesn't get in the way.
