### ISSUE TITLE
Valid config options are flagged as "unrecognized"

### ISSUE THREAD

**Issue by PikalaxALT** [nextflow-io/language-server#50]
Examples:
`validation.lenientMode`
`mail.smtp.host`
`mail.smtp.port`
`weblog.enabled`
`weblog.url`

There could be broader categories of config options which are documented for the base language or provided by a plugin, but these are the ones I use in my projects that are being flagged.

**Comment by bentsherman** [comment]
Thanks for flagging. The mail config options I simply forgot to include, the other options are coming from plugins which aren't recognized by the language server yet. All plugins will need to be updated to explicitly define the config options that they expose, and there are a few moving parts involved in that
