### ISSUE TITLE
Nextflow language server crashes: this version of the Java Runtime only recognizes class file versions up to 55.0

### ISSUE THREAD

**Issue by nschan** [nextflow-io/language-server#58]
Hello,

I am unable to run the nextflow language server in VSCode. I receive this error:

```
Error: LinkageError occurred while loading main class nextflow.lsp.NextflowLanguageServer
	java.lang.UnsupportedClassVersionError: nextflow/lsp/NextflowLanguageServer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
  Code: -32097 
```

The system I use is old, so I assume this is the reason, but I could not find a mention of the minimum requirements for this plugin anywhere.

**Comment by nschan** [comment]
This is probably a duplicate of this https://github.com/nextflow-io/vscode-language-nextflow/issues/35 ; sorry I did not realize that there were two different repos for this.

**Comment by bentsherman** [comment]
No problem. Was your issue that you were using Java 11? Minimum requirement is Java 17, but we're also seeing errors like this even for users with Java 17, so we're still investigating that

**Comment by nschan** [comment]
Yes, I am using Java 11.

**Comment by bentsherman** [comment]
Upgrading to 17 should make things work. Let me know if it still crashes
