### ISSUE TITLE
Stripping ,s in arguements with formatting

### ISSUE THREAD

**Issue by edmundmiller** [nextflow-io/language-server#60]
I try to leave a trailing `,` in arguements of functions to avoid having a more complicated diff when adding another arugment later.

The formatter is fighting me on that:

```diff
    PINTS_CALLER(
        group_bam_bai.combine(ch_chr),
-        params.assay_type,
+        params.assay_type
    )
```

I think this is common in Python formatters, and it's [an option in Prettier](https://prettier.io/docs/en/options.html#trailing-commas)

**Comment by bentsherman** [comment]
Resolved by f0301f2a
