### ISSUE TITLE
nextflow.config unrecognized config options false positives

### ISSUE THREAD

**Issue by VasLem** [nextflow-io/language-server#61]
In my config there are:
```
executor.retry.delay = 300000
google.storage.parallelThreadCount = 2
google.storage.maxTransferAttempts = 3
```

all of which options are mentioned in the [documentation](https://www.nextflow.io/docs/latest/reference/config.html) . I am not sure if there are more options with this issue, but I am getting `Unrecognized config option` false positive warning. Or is it actually that those options are not supported after all?

**Comment by bentsherman** [comment]
I forgot about the executor retry options, so they will be added in 1.0.1

Those google storage options are only used for Google Life Sciences. Are you still using that? It is going to be taken down next year

**Comment by VasLem** [comment]
Thanks, so why are these options related to Google Life Sciences and not Google Batch? As far as I can tell `google.lifeSciences.` prefix is used for the Google Life Sciences ones and `google.` for the Google Batch, doesn't this hold?

**Comment by bentsherman** [comment]
Yes, but the `google.storage` options are mixed. If you go to the [docs](https://nextflow.io/docs/latest/reference/config.html#google) you will see which options are defined for batch vs life sciences.
