### ISSUE TITLE
Reference to Groovy class in package is unknown 

### ISSUE THREAD

**Issue by henrjk** [nextflow-io/language-server#65]
With a Groovy class implemented in `lib/extra/Tools.groovy` as: 

```Groovy
package extra
class Tools {
    public static void someFunction() {
         // some code
    }
}
```

And in a workflow file at `workflows/extra/demos/hello-world.nf`:

```
// import extra.Tools leads to message:  
//   Groovy `import` declarations are not supported -- use fully-qualified name inline instead
workflow BIX_DEMO_HELLO_WORLD {
    extra.Tools.someFunction().  // this leads to message:  extra is unknown
}
```

**Comment by bentsherman** [comment]
Great, that makes things easier. We just need to walk the entire directory tree and respect the package declarations. I will try to include this in the next update

**Comment by bentsherman** [comment]
After some testing I found that it's actually the opposite of what I expected. The package declaration seems to be completely ignored, and instead is inferred entirely from the directory structure

Meanwhile, the language server is already walking the entire directory tree, so it will pick up `lib/extra/Tools.groovy`. The language server also seems to be ignoring the package declaration.

So, the language server just needs to be updated to infer the package name from the directory structure

**Comment by bentsherman** [comment]
Will be fixed in the next patch release
