### ISSUE TITLE
Spread operator removed on save

### ISSUE THREAD

**Issue by eweizy** [nextflow-io/language-server#70]
When formatting on save I am running into an issue where the spread operator `*` gets removed from my code

For example, given a code block
```
    ch_vcf
        .map { meta, vcf, index ->
            def new_meta = meta.clone()
            new_meta.id = "${new_meta.sample}_${new_meta.reference}"
            [new_meta, vcf, index]
        }
        .map { meta, vcf, index ->
            [meta.subMap(meta.keySet() - ['chrom']), [vcf, index, meta.chrom]]
        }
        .groupTuple(sort: { it[2] })
        .map { tuple(it[0], it[1]*.get(0), it[1]*.get(1)) }
        .dump(tag: 'ch_bcftools_concat_chroms_in')
        .set { ch_bcftools_concat_chroms_in }
```

upon saving I end up with 
```
    ch_vcf
        .map { meta, vcf, index ->
            def new_meta = meta.clone()
            new_meta.id = "${new_meta.sample}_${new_meta.reference}"
            [new_meta, vcf, index]
        }
        .map { meta, vcf, index ->
            [meta.subMap(meta.keySet() - ['chrom']), [vcf, index, meta.chrom]]
        }
        .groupTuple(sort: { it[2] })
        .map { tuple(it[0], it[1].get(0), it[1].get(1)) } 
        .dump(tag: 'ch_bcftools_concat_chroms_in')
        .set { ch_bcftools_concat_chroms_in }
```

where the spread operators in the last `map` operator are removed.

Is this due to the strict syntax and if so what alternative is available for the spread operator?

**Comment by bentsherman** [comment]
Good catch. Looks like I forgot to include the spread dot and safe dot in the formatting. I will get that fixed in the next release.

In case you're curious, here is the equivalent syntax: https://github.com/nextflow-io/language-server/blob/ab8e4d51ce101c554ba3c57f3c62b7aa3d24c721/src/main/antlr/ScriptParser.g4#L457-L460
