### ISSUE TITLE
channels in emit have trailing spaces when they don't get assigned if just 1 is assigned

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/language-server#79]
let's say I have:
```
    emit:
    bowtie1
    bowtie2
    bwamem1
    fasta = input.fasta
```

when I save my script, (with the Harshil alignment), it's adding spaces after the output channels in emit so that all `=` are aligned, but when I only have 1 `=`, it just adds trailing spaces.

**Comment by bentsherman** [comment]
This should be fixed in the latest version

**Comment by maxulysse** [comment]
Wonderful
