### ISSUE TITLE
issue with def in nf-core nextflow.config

### ISSUE THREAD

**Issue by maxulysse** [nextflow-io/language-server#80]
It got caught up in a loop, I was first a warning on the `n` of nextflow warning me about the def that should not be there.
If I apply the fix, then the warning is on the `f` of nextflow, saying that I need the def
and so on...

```nextflow
// Disable process selector warnings by default. Use debug profile to enable warnings.
nextflow.enable.configProcessNamesValidation = false

def trace_timestamp = new java.util.Date().format( 'yyyy-MM-dd_HH-mm-ss')
```

**Comment by bentsherman** [comment]
I think this is being addressed in the pipeline template: https://github.com/nf-core/tools/issues/3294

**Comment by maxulysse** [comment]
Thanks
