### ISSUE TITLE
Error with 'optional' keywords with tuple

### ISSUE THREAD

**Issue by phoenix-yyj** [nextflow-io/language-server#81]
Nextflow doc says output in process can have the keywork `optional`

like:
```
output:
path("output.txt"), optional: true
```
it works well with `path`,but when come to `tuple`
```
output:
tuple(path("output.txt"),vale(meta)), optional: true
```
an error occured
```
Unexpected input: ','
```
however,as the doc's note says
> While this option can be used with any process output, it cannot be applied to individual elements of a [tuple](https://nextflow.io/docs/latest/process.html#output-tuples-tuple) output. The entire tuple must be optional or not optional.

is there anything i miss in doc?

**Comment by bentsherman** [comment]
It should work if you write it like this:
```groovy
output:
tuple path("output.txt"), val(meta), optional: true
```

**Comment by phoenix-yyj** [comment]
> It should work if you write it like this:
> 
> ```groovy
> output:
> tuple path("output.txt"), val(meta), optional: true
> ```

it's works ,thank you very much.
by the why ,i wonder if the language server would support tuple with quotes?
as the [Output Doc](https://nextflow.io/docs/latest/reference/process.html#outputs) shows tuple would like
```
tuple( arg1, arg2, ... )
```

**Comment by bentsherman** [comment]
The correct way to use parentheses would be:
```groovy
output:
tuple( path("output.txt"), val(meta), optional: true )
```
