### ISSUE TITLE
`sleep` is not defined

### ISSUE THREAD

**Issue by phoenix-yyj** [nextflow-io/language-server#83]
the same code in [Doc](https://www.nextflow.io/docs/latest/process.html#dynamic-retry-with-backoff) would throw out an error
```
errorStrategy {
        sleep(Math.pow(2, task.attempt) * 200 as long)
        return 'retry'
}
```
throw `sleep is not defined`
did i miss anything?

**Comment by bentsherman** [comment]
Thanks for reporting, I will add it for the next release
