### ISSUE TITLE
sleep is not defined in process errorStrategy

### ISSUE THREAD

**Issue by mcolpus** [nextflow-io/language-server#85]
I have this line in a process
```
errorStrategy { sleep(Math.pow(2, task.attempt) * 60 as long); return 'retry' } //seconds
```
The `sleep` is highlighted as having the error: "`sleep` is not defined"
This syntax matches the nextflow docs: https://www.nextflow.io/docs/latest/process.html#dynamic-retry-with-backoff

I'm using nextflow extension in vscode 1.0.2

**Comment by bentsherman** [comment]
duplicate of #83 

will be fixed in the next patch release
